### ISSUE TITLE
Should I replace django by django_structlog?

### ISSUE THREAD

**Issue by Calzzetta** [jrobichaud/django-structlog#43] opened 2020-08-05 22:46 UTC
Hi @jrobichaud,

In the README is:
> Logging will then produce additional cohesive metadata on each logs that makes it easier to track events or incidents.

Should I keep `django` and `django_structlog` in my `LOGGING['loggers']` or `django_structlog` will replace `django` logs?

Regards,
Douglas

**Comment by jrobichaud** [comment] 2020-08-06 00:27
Hi @Calzzetta 

`django-structlog` does not replace [django loggers](https://docs.djangoproject.com/en/dev/topics/logging/#id3) (Except maybe `django.request` logger as designed). 

You could keep both depending of your needs but you have to configure them separately. Since django use python default logger we cannot inject `structlog` to replace their logger (as least we have not figured it out yet, see #24).

The goal of this library is to correlate user requests and the logs you create in your code.

Ex: 
- User submit a form
- django-structlog log request with an unique id
- You log stuff
- You enqueue a celery task (django-structlog log this as well automatically)
- You Log stuff in task

Everything can be tracked back to the source request.

You could try the [demo project](https://django-structlog.readthedocs.io/en/latest/demo.html) to test it.

See the [full documentation](https://django-structlog.readthedocs.io/en/latest/getting_started.html) for more details.

I will close this, I hope I fully answered your question (you can still comment on this topic if necessary).

Feel free to open issues if you encounter problems.

Thank you.

**Closed** 2020-08-06 00:27 UTC
